### PR TITLE
new API hostname and ability to change hostname in client options

### PR DESCRIPTION
**Pull request by iandouglas**
Users will connect to our new .com domain in case another .io TLD problem happens. Users can also set `options[:api_hostname]` when instantiating the API client to set their own domain name.

### CODE REVIEW

**Comment by iandouglas** [comment]
@tbarbugli PR should be all set, includes some SNI testing and should ensure the old getstream.io hostname should still pass the regex pattern for Heroku users. (could possibly simplify it by combining both hostnames into a single regex but I'd prefer to be more explicit about it for a first pass)

**Comment by dwightgunning** [comment]
Do we mind that any existing Heroku app with the STREAM_URL environment variable in the form `<username>:<password>@api.getstream.io/?app_id=<app id>` will actually connect to the new `stream-io-api.com` domain?

In the feature branch I was working on for this card I had updated the regex so use the domain set in configuration.

**Comment by dwightgunning** [comment]
I've piled on with a minor change to the README.md to outline minimum/supported versions in a way that's consistent with the other libraries.

**Comment by dwightgunning** [comment]
Discussed in person with Tommaso. We're good to merge.

**Pull request merged**
