### PR TITLE
Implement Stream::Feed#readonly_token

### PR DESCRIPTION
**Pull request by kennym**

### CODE REVIEW

**Comment by kennym** [comment]
Partially implements #47

**Comment by tbarbugli** [comment]
looks like the right approach. Since you are working on it I suggest we use JWT instead of the signature for everything in the feed class (you can use the python client as a reference)

**Comment by kennym** [comment]
@tbarbugli that would be awesome - what about merging this one and I'll open another PR, as this would of the scope of the current PR

**Comment by tbarbugli** [comment]
sure, btw make sure that you specifically use the HS256 algorithm and that timestamp are not part of the token when you create them with JWT.

**Comment by kennym** [comment]
[x] Specifically use HS256
[x] Do not use Timestamp as part of payload

The Ruby JWT library doesn't provide you with a nice option as the JS JWT library you use for `stream-js`, but the default is that no `IaT` "(Issued At) Claim" payload is specified. So, no need to do anything: https://github.com/jwt/ruby-jwt/blob/master/lib/jwt.rb#L113

**Pull request merged**
