### PR TITLE
Have feed requests match client make_request signature

### PR DESCRIPTION
**Pull request by volksport**
Current gem release breaks removing via foreign_id, and using count/limit for following/followers. Patch fixes. I also suggest a new gem release.

### CODE REVIEW

**Comment by kennym** [comment]
That looks good. Thank you!

Specs would be awesome

**Comment by volksport** [comment]
Not to be rude, but I don't intend to write specs for this. If the current specs had a proper mocked and inspectable client, I would... but at the moment the test would have to do a write and a read against the actual API.

**Comment by tbarbugli** [comment]
thank you for the patch! going to merge it and release today

**Comment by tbarbugli** [comment]
2.3.1 is now available

**Pull request merged**
